-- Insert all services data
INSERT INTO public.servicios (tipo, categoria, servicio, producto, variante, precio) VALUES
('contabilidad', 'ASESORÍA Y CONSULTORÍA', 'Consulta en oficina', NULL, NULL, 100),
('contabilidad', 'ASESORÍA Y CONSULTORÍA', 'Consulta en Instalaciones de Cliente', NULL, NULL, 200),
('contabilidad', 'ASESORÍA Y CONSULTORÍA', 'Viaje Fuera de Ciudad', NULL, NULL, 1000),
('contabilidad', 'AUDITORÍAS FINANCIERAS', 'AUDITORIAS DOCUMENTARIAS', NULL, NULL, 2000),
('contabilidad', 'AUDITORÍAS FINANCIERAS', 'AUDITORIAS TRIBUTARIAS', NULL, NULL, 5000),
('contabilidad', 'AUDITORÍAS FINANCIERAS', 'AUDITORIAS LABORALES', NULL, NULL, 8000),
('contabilidad', 'AUDITORÍAS FINANCIERAS', 'AUDITORIAS ADMINISTRATIVAS', NULL, NULL, 10000),
('contabilidad', 'AUDITORÍAS FINANCIERAS', 'AUDITORIAS FINANCIERAS SIMPLES', NULL, NULL, 20000),
('contabilidad', 'AUDITORÍAS FINANCIERAS', 'AUDITORIAS FINANCIERAS COMPLETAS', NULL, NULL, 25000),
('contabilidad', 'CAPACITACIÓN CONTABLE', 'Capacitación Grupal Empresarial', NULL, NULL, 50),
('contabilidad', 'CAPACITACIÓN CONTABLE', 'Capacitación Individual Empresarial', NULL, NULL, 50),
('contabilidad', 'CONSTITUCIONES', 'CONSTITUCION DE EMPRESA SIMPLE (PRODUCE)', NULL, NULL, 300),
('contabilidad', 'CONSTITUCIONES', 'CONSTITUCION DE EMPRESA', 'DE 0  A 20, 000.00  SOLES', NULL, 500),
('contabilidad', 'CONSTITUCIONES', 'CONSTITUCION DE EMPRESA', 'DE 21,000.00 A MAS', NULL, 1000),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION MENSUAL DE RENTA 1ERA.2DA.4TA.5TA.', NULL, NULL, 100),
('contabilidad', 'DECLARACION ANUAL', 'DECLARACION ANUAL DE RENTA 1ERA.2DA.4TA.5TA.', 'sin compras, sin ventas', NULL, 200),
('contabilidad', 'DECLARACION ANUAL', 'DECLARACION ANUAL P. J. - PYME', 'DE 10,000 A 120,000 SOLES', NULL, 500),
('contabilidad', 'DECLARACION ANUAL', 'DECLARACION ANUAL P. J. - PYME', 'DE 121,000 A 200,000 SOLES', NULL, 1000),
('contabilidad', 'DECLARACION ANUAL', 'DECLARACION ANUAL P. J. - PYME', 'DE 201,000.00 A MAS', NULL, 1500),
('contabilidad', 'DECLARACION ANUAL', 'DECLARACION ANUAL P. J. - R.G.', 'DE 10,000 A 120,000 SOLES', NULL, 1000),
('contabilidad', 'DECLARACION ANUAL', 'DECLARACION ANUAL P. J. - R.G.', 'DE 121,000 A 200,000 SOLES', NULL, 1500),
('contabilidad', 'DECLARACION ANUAL', 'DECLARACION ANUAL P. J. - R.G.', 'DE 201,000.00 A MAS', NULL, 2000),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION MENSUAL RER', 'DE 0  A 10 MIL SOLES', NULL, 100),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION MENSUAL RER', 'DE 11,000 A 20,000 SOLES', NULL, 150),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION MENSUAL RER', 'DE 21, 000 A MAS', NULL, 200),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION MYPE', 'DE 0 A 50 MIL', NULL, 200),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION MYPE', 'DE 51 MIL A 100 MIL', NULL, 300),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION MYPE', 'DE 101 MIL A 200 MIL', NULL, 500),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION MYPE', 'DE 201 MIL A 400 MIL', NULL, 1000),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION MYPE', 'DE 400 MIL A MAS', NULL, 1500),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION REGIMEN GENERAL', 'DE 0 A 50 MIL', NULL, 500),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION REGIMEN GENERAL', 'DE 51 MIL A 100 MIL', NULL, 1000),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION REGIMEN GENERAL', 'DE 101 MIL A 200 MIL', NULL, 1500),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION REGIMEN GENERAL', 'DE 201 MIL A 400 MIL', NULL, 2000),
('contabilidad', 'CONTABILIDAD INTEGRAL', 'DECLARACION REGIMEN GENERAL', 'DE 401 A MAS', NULL, 3000),
('contabilidad', 'CONTROL INTERNO', 'IMPLEMENTACION DE CONTROL INTERNO', NULL, NULL, 5000),
('contabilidad', 'CONTROL INTERNO', 'MONITOREO DE CONTROL INTERNO', NULL, NULL, 2000),
('contabilidad', 'CO-WORKING', 'Oficina compartida + sala de reuniones + servicio de cafeteria', 'HORA', NULL, 50),
('contabilidad', 'CO-WORKING', 'Oficina compartida + sala de reuniones + servicio de cafeteria', 'DIA', NULL, 350),
('contabilidad', 'CO-WORKING', 'Oficina compartida + sala de reuniones + servicio de cafeteria', 'SEMANA', NULL, 1500),
('contabilidad', 'CENTRO DE TRÁMITES', 'LICENCIA DE FUNCIONAMIENTO Y CERT. DEFENSA CIVIL', NULL, NULL, 200),
('contabilidad', 'CENTRO DE TRÁMITES', 'LICENCIA PERMISO PARA LETREROS', NULL, NULL, 200),
('contabilidad', 'Marketing', 'Branding y Creacion de Logo', 'Creación de Logo sin Manual de Marca', 'SIMPLE', 250),
('contabilidad', 'Marketing', 'Branding y Creacion de Logo', 'Creación de Logo con Manual de Marca', NULL, 400),
('contabilidad', 'Marketing', 'Branding y Creacion de Logo', 'Rebranding', NULL, 400),
('contabilidad', 'Marketing', 'Branding y Creacion de Logo', 'Letreros', NULL, 0),
('contabilidad', 'Marketing', 'Branding y Creacion de Logo', 'Mechandising', NULL, 0),
('contabilidad', 'Marketing', 'Gestión de Redes Sociales', 'Diseño de Post', NULL, 30),
('contabilidad', 'Marketing', 'Gestión de Redes Sociales', 'Diseño de Reel', NULL, 80),
('contabilidad', 'Marketing', 'Gestión de Catálogo / Brochure', 'Elaboración de Catálogo', 'Con Diseño Web sin  Dominio', 400),
('contabilidad', 'Marketing', 'Gestión de Catálogo / Brochure', 'Elaboración de Catálogo', 'Con Diseño Web con Dominio', 600),
('contabilidad', 'Marketing', 'Gestión de Catálogo / Brochure', 'Elaboración de Catálogo', 'Sin Diseño Web', 200),
('contabilidad', 'Marketing', 'Gestión de Catálogo / Brochure', 'Elaboración de Brochure', 'Con Diseño Web sin  Dominio', 400),
('contabilidad', 'Marketing', 'Gestión de Catálogo / Brochure', 'Elaboración de Brochure', 'Con Diseño Web con Dominio', 600),
('contabilidad', 'Marketing', 'Gestión de Catálogo / Brochure', 'Elaboración de Brochure', 'Sin Diseño Web', 200),
('contabilidad', 'OUTSOURCING CONTABLE', 'Selección, capacitación y destaque sin plla', NULL, NULL, 2200),
('contabilidad', 'OUTSOURCING CONTABLE', 'Selección, capacitación y destaque con plla', NULL, NULL, 1200),
('contabilidad', 'PLANILLAS', 'DE 1 A 4 TRABAJADORES', NULL, NULL, 50),
('contabilidad', 'PLANILLAS', 'DE 5 A 10 TRABAJADORES', NULL, NULL, 100),
('contabilidad', 'PLANILLAS', 'DE 10 A 30 TRABAJADORES', NULL, NULL, 500),
('contabilidad', 'PLANILLAS', 'DE 30 A 60 TRABAJADORES', NULL, NULL, 1000),
('contabilidad', 'PLANILLAS', 'DE 61 A 100 TRABAJADORES', NULL, NULL, 1500),
('contabilidad', 'Sistemas Integrados de Gestión', 'Auditoría Interna ISO 9001', NULL, NULL, 15000),
('contabilidad', 'Sistemas Integrados de Gestión', 'Auditoría al Sistema de Gestión de Seguridad y Salud en el Trabajo', 'Matrices IPERC', NULL, 5000),
('contabilidad', 'Sistemas Integrados de Gestión', 'Auditoría al Sistema de Gestión de Seguridad y Salud en el Trabajo', 'Mapas de Riesgos', NULL, 6000),
('contabilidad', 'Sistemas Integrados de Gestión', 'Auditoría al Sistema de Gestión de Seguridad y Salud en el Trabajo', 'Estándares Operativos y de Gestión en SST', NULL, 4000),
('contabilidad', 'Sistemas Integrados de Gestión', 'Auditoría al Sistema de Gestión de Seguridad y Salud en el Trabajo', 'Programa Anual de SST', NULL, 10000),
('contabilidad', 'Sistemas Integrados de Gestión', 'Auditoría al Sistema de Gestión de Seguridad y Salud en el Trabajo', 'Reglamento Interno de SST', NULL, 8000),
('contabilidad', 'Sistemas Integrados de Gestión', 'Capacitación', 'PRECIO POR ALUMNO Y POR DIA', NULL, 100),
('contabilidad', 'TOMA DE INVENTARIOS FISICOS', 'INVENTARIOS SIMPLE (1-200 ITEMS)', NULL, NULL, 500),
('contabilidad', 'TOMA DE INVENTARIOS FISICOS', 'INVENTARIOS COMPLETOS (200-1000 ITEMS)', NULL, NULL, 1300),
('tramites', 'CENTRO DE TRÁMITES', 'JUBILACION AFP', NULL, NULL, 150),
('tramites', 'CENTRO DE TRÁMITES', 'FONAVI', NULL, NULL, 50),
('tramites', 'CENTRO DE TRÁMITES', 'INSCRIPCIÓN A LA OSCE/RNP (PROVEEDOR SIMPLE)', NULL, NULL, 70),
('tramites', 'CENTRO DE TRÁMITES', 'INSCRIPCIÓN A LA OSCE/RNP (PROVEEDOR COMPLETO)', NULL, NULL, 150),
('tramites', 'CENTRO DE TRÁMITES', 'VIGENCIA DE PODER SUNATVIGENCIA DE PODER SUNARP', NULL, NULL, 100),
('tramites', 'CENTRO DE TRÁMITES', 'TRAMITES RENIEC', NULL, NULL, 30),
('tramites', 'CENTRO DE TRÁMITES', 'BUSQUEDAS -SUNARP- COPIAS LITERALES ETC.', NULL, NULL, 50),
('tramites', 'CENTRO DE TRÁMITES', 'ACTUALIZACIÓN DE DATOS SIMPLE RUC', NULL, NULL, 50),
('tramites', 'CENTRO DE TRÁMITES', 'ALTA, BAJA SUSPENSION RUC', NULL, NULL, 50),
('tramites', 'CENTRO DE TRÁMITES', 'RECUPERACIÓN DE CLAVE SOL', NULL, NULL, 50),
('tramites', 'CENTRO DE TRÁMITES', 'CONSTANCIA DE SUSPENCIÓN RENTA DE 4TA', NULL, NULL, 50),
('tramites', 'CENTRO DE TRÁMITES', 'REGISTRO DE MARCA', NULL, NULL, 300),
('tramites', 'CONTABILIDAD INTEGRAL', 'DECLARACION MENSUAL RUS', NULL, NULL, 50),
('tramites', 'CENTRO DE TRÁMITES', 'INSCRIPCION AL RUC', NULL, NULL, 50),
('tramites', 'CENTRO DE TRÁMITES', 'REPORTE DE RENTA DE 4TA, 5TA', NULL, NULL, 50),
('tramites', 'CENTRO DE TRÁMITES', 'SOLICITUD DE DEVOLUCION DE PERCEPCIONES', NULL, NULL, 100),
('tramites', 'CENTRO DE TRÁMITES', 'TRAMITES EN MINISTERIOS', NULL, NULL, 300),
('tramites', 'CENTRO DE TRÁMITES', 'ESSALUD', NULL, NULL, 150);